generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
  - name: tls-secret
    namespace: logstash
    files:
      - keystore.jks
      - truststore.jks
      - KAFKA_SSL_PWD
  - name: tls-secret
    namespace: default
    files:
      - crt
      - key
      - cacert
      - keystore.jks
      - truststore.jks
      - KAFKA_SSL_PWD
  - name: tls-secret
    namespace: argo-events
    files:
      - crt
      - key
      - cacert
resources:
  - mongo-secret-mongo.yaml
  - logstash-env.yaml
  - ml-env.yaml
  - s3-secret.yaml
