---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: podinfo
  namespace: default
spec:
  interval: 3m
  ref:
    branch: master
  url: https://github.com/stefanprodan/podinfo
