---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgres
  namespace: default
spec:
  interval: 2m0s
  releaseName: postgres
  targetNamespace: default
  chart:
    spec:
      chart: postgresql
      sourceRef:
        kind: HelmRepository
        name: bitnami
      version: ">10.15.0"
  # !! charts are created in the same ns as the repo - and secrets are read from the same ns too - here: default everywhere
  # Using SECRET as helm values
  # Option 1 most generic ; using the helm controller valuesFrom option https://fluxcd.io/docs/guides/helmreleases/#refer-to-values-in-configmap-and-secret-resources
  # make sure you enquote the password to avoid JSON decoding error
  # valuesFrom:
  #   - kind: Secret
  #     name: postgres-secrets
  #     valuesKey: postgresql-password
  # targetPath:
  #option2 https://github.com/bitnami/charts/tree/master/bitnami/postgresql/#parameters
  # make sure the data key is postgresql-password
  # values:
  #   existingSecret: postgres-secrets
  # option 3:
  # - usePasswordFile
  values:
    service:
      type: LoadBalancer
    existingSecret: postgres-secrets
