apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
  - name: bag
    namespace: default
    files:
      - crt
      - KAFKA_SSL_PWD
  - name: ml.env
    namespace: default
    envs:
      - ml.env
resources:
  - samplesecretplain.yaml
  - samplesecret.sops.yaml
  - samplesecretkubeseal.yaml
  - postgres_secrets.sops.yaml
